### PR TITLE
Fix PE-D Bug

### LINKED ISSUE #192: [PE-D] Need for defensiveness in addR command
Great work on the addR feature. It's quite complex, but it generally works.

A minor nit:

To reproduce:
use `addR n/Chicken salad i/chicken - 100g, lettuce - a bit, tomato c/100 instr/Cook. Eat.  .  .  .         img/images/salad.jpg t/healthy t/delicious`

Result:

Expected:
Just
1. Cook
2. Eat

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: lowjiefeng1998/ped#4

### LINKED ISSUE #193: [PE-D] Similar bug to the other addR
This might not be a bug pe se, but it is quite strange:

To reproduce:

use addR n/Chicken salad i/chicken - 100g, lettuce - a bit, tomato c/100 instr/Cook. Eat. . . . .img/images/salad.jpg t/healthy t/delicious

Result:

Expected:
Same as before, just cook and eat.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: lowjiefeng1998/ped#5

### LINKED ISSUE #195: [PE-D] Changing of json file in addR
I'm sorry.

This output is possible:

Steps to reproduce:
1. Use addR's sample example
2. Exit the program. Delete instruction 1. Resulting data file is:

Recommendation:
Try to read the json field as an array instead i.e. remove 1) ... from the instruction steps

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: lowjiefeng1998/ped#7

### LINKED ISSUE #220: [PE-D] Adding Img not working sometimes
Tested adding img with this URL https://gutta.lv/wp-content/uploads/2015/10/test-img.jpg

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: todoge/ped#1

### LINKED ISSUE #223: [PE-D] No instruction recipe is accepted
No instruction recipe is accepted. It should not be accepted because a no instruction recipe is not a recipe.
 

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: todoge/ped#4

### PR DESCRIPTION
**Pull request by jiaqi20**

### CODE REVIEW

**Review by caitlinjee — APPROVED** [review]
lgtm

**Review by TianYong-Goh — APPROVED** [review]
lgtm

File: src/main/java/seedu/address/logic/commands/recipe/EditRecipeCommand.java [hunk 1]
```diff
@@ -64,7 +64,9 @@
     public static final String MESSAGE_EDIT_RECIPE_SUCCESS = "Edited Recipe: %1$s";
     public static final String MESSAGE_NOT_EDITED = "No edit made. At least one field to edit must be provided.";
     public static final String MESSAGE_DUPLICATE_RECIPE = "This recipe already exists in the Recipe collection.";
+    public static final String MESSAGE_EMPTY_INSTRUCTIONS = "This instructions for recipe cannot be empty.";
```
Comment (oliviajohansen) [inline src/main/java/seedu/address/logic/commands/recipe/EditRecipeCommand.java]: can keep the message consistent between addRecipeCommand and editRecipe command? Either 1) "This recipe must contain instruction."; or 2) "This instructions for recipe cannot be empty.";. I suggest 1) since it follows the format of other message constraints

File: src/main/java/seedu/address/logic/parser/recipe/AddRecipeCommandParser.java [hunk 2]
```diff
@@ -69,6 +69,10 @@ public AddRecipeCommand parse(String args) throws ParseException, IOException, U
         String instructionString = argMultimap.getValue(PREFIX_INSTRUCTION).get();
         ArrayList<Instruction> instructions = InstructionParser.parse(instructionString);
 
+        if (instructions.size() == 0) {
```
Comment (oliviajohansen) [inline src/main/java/seedu/address/logic/parser/recipe/AddRecipeCommandParser.java]: isnt this exact if statement already checked in instructionparser? is it redundant? maybe an assert would be better?

File: src/main/java/seedu/address/logic/parser/recipe/EditRecipeCommandParser.java [hunk 3]
```diff
@@ -66,26 +67,34 @@ public EditRecipeCommand parse(String args) throws ParseException, IOException,
...
+        }
         if (argMultimap.getValue(PREFIX_INSTRUCTION).isPresent()) {
             String instructionString = argMultimap.getValue(PREFIX_INSTRUCTION).get();
             ArrayList<Instruction> instructions = InstructionParser.parse(instructionString);
             editRecipeDescriptor.setInstruction(instructions);
-        }
-        if (argMultimap.getValue(PREFIX_CALORIES).isPresent()) {
-            Calories calories = ParserUtil.parseCalories(argMultimap.getValue(PREFIX_CALORIES).get());
-            editRecipeDescriptor.setCalories(calories);
+            if (instructions.size() == 0) {
```
Comment (oliviajohansen) [inline src/main/java/seedu/address/logic/parser/recipe/EditRecipeCommandParser.java]: same inst it checked in instructionparser

**Review by oliviajohansen — COMMENTED** [review]
lgb

File: src/main/java/seedu/address/logic/parser/data/InstructionParser.java [hunk 4]
```diff
@@ -16,12 +18,18 @@
...
-            String instr = (i + 1) + ") " + instructionsToken[i].trim();
-            instructions.add(new Instruction(instr));
+            if (!instructionsToken[i].trim().equals("")) {
+                String instr = instructionsToken[i].trim();
+                instructions.add(new Instruction(instr));
+            }
+        }
+        if (instructions.size() == 0) {
+            throw new ParseException(String.format(MESSAGE_INVALID_COMMAND_FORMAT,
+                    "Instruction cannot be empty"));
```
Comment (oliviajohansen) [inline src/main/java/seedu/address/logic/parser/data/InstructionParser.java]: shouldnt the message of the parseException be like AddRecipeCommand.MESSAGE_EMPTY_INSTRUCTIONS instead of hard coded

**Review by oliviajohansen — COMMENTED** [review]
this also

**Review by daongochieu2810 — APPROVED** [review]

**Review by oliviajohansen — APPROVED** [review]
lgtm
